// Copyright (c) Microsoft. All rights reserved.

package textsearch

import (
	"context"
	"encoding/json"
	"strings"
	"sync"

	"github.com/microsoft/agent-framework-go/agent"
	"github.com/microsoft/agent-framework-go/chat"
	"github.com/microsoft/agent-framework-go/tool"
)

// providerMarker is the Name value used to mark messages generated by this provider.
// This allows us to filter out our own messages to prevent feedback loops.
const providerMarker = "textsearch-context-provider"

// Provider implements RAG (Retrieval Augmented Generation) by searching
// for relevant context before or during agent invocations.
//
// It supports two modes:
//   - BeforeAIInvoke: Automatically search and inject context before each invocation
//   - OnDemandFunctionCalling: Expose search as a tool the model can invoke
//
// The provider tracks conversation history to build effective search queries
// from the full context of the conversation.
type Provider struct {
	agent.BaseContextProvider

	search  SearchFunc
	options Options

	// Memory of recent messages for context building
	memory []agent.Message
	mu     sync.Mutex

	// Pre-built search tool for OnDemandFunctionCalling mode
	searchTool tool.Tool
}

// New creates a new text search provider.
//
// The search function is called to retrieve relevant documents or information.
// Configure behavior using Option functions.
func New(search SearchFunc, opts ...Option) *Provider {
	options := defaultOptions()
	for _, opt := range opts {
		if opt != nil {
			opt(&options)
		}
	}

	p := &Provider{
		search:  search,
		options: options,
		memory:  make([]agent.Message, 0),
	}

	// Pre-build search tool for on-demand mode
	if options.SearchBehavior == OnDemandFunctionCalling {
		p.searchTool = p.buildSearchTool()
	}

	return p
}

// searchArgs is the argument structure for the search tool.
type searchArgs struct {
	Query string `json:"query" description:"The search query to find relevant information"`
}

// buildSearchTool creates the search function tool.
func (p *Provider) buildSearchTool() tool.Tool {
	searchFn := func(ctx context.Context, args searchArgs) (string, error) {
		results, err := p.search(ctx, args.Query)
		if err != nil {
			return "", err
		}
		return p.formatResults(results), nil
	}

	t, err := tool.NewFunctionTool(
		p.options.SearchToolName,
		p.options.SearchToolDescription,
		searchFn,
	)
	if err != nil {
		// This should not happen with our valid function signature
		panic("textsearch: failed to create search tool: " + err.Error())
	}

	return t
}

// formatResults formats search results into a string.
func (p *Provider) formatResults(results []SearchResult) string {
	if p.options.ResultFormatter != nil {
		return p.options.ResultFormatter(results)
	}
	return p.defaultFormatResults(results)
}

// defaultFormatResults provides the default result formatting.
func (p *Provider) defaultFormatResults(results []SearchResult) string {
	if len(results) == 0 {
		return ""
	}

	var sb strings.Builder
	sb.WriteString(p.options.ContextPrompt)
	sb.WriteString("\n\n")

	for i, result := range results {
		if i > 0 {
			sb.WriteString("\n----\n")
		}

		if result.Name != "" {
			sb.WriteString("**")
			sb.WriteString(result.Name)
			sb.WriteString("**\n")
		}

		if result.Link != "" {
			sb.WriteString("Source: ")
			sb.WriteString(result.Link)
			sb.WriteString("\n")
		}

		sb.WriteString(result.Value)
	}

	if p.options.CitationsPrompt != "" {
		sb.WriteString("\n\n")
		sb.WriteString(p.options.CitationsPrompt)
	}

	return sb.String()
}

// extractTextFromMessages builds a query string from messages.
func (p *Provider) extractTextFromMessages(messages []agent.Message) string {
	var sb strings.Builder

	// Include memory first
	for _, msg := range p.memory {
		if text := extractMessageText(msg); text != "" {
			sb.WriteString(text)
			sb.WriteString(" ")
		}
	}

	// Include current messages
	for _, msg := range messages {
		if text := extractMessageText(msg); text != "" {
			sb.WriteString(text)
			sb.WriteString(" ")
		}
	}

	return strings.TrimSpace(sb.String())
}

// extractMessageText extracts text content from a message.
func extractMessageText(msg agent.Message) string {
	// Use the Text() method which handles Contents slice
	return msg.Text()
}

// Invoking is called before each agent invocation.
//
// In BeforeAIInvoke mode, this method performs a search and injects
// results as a context message.
//
// In OnDemandFunctionCalling mode, this method returns the search tool.
func (p *Provider) Invoking(ctx context.Context, messages []agent.Message) (*agent.Context, error) {
	switch p.options.SearchBehavior {
	case BeforeAIInvoke:
		return p.invokingBeforeAI(ctx, messages)
	case OnDemandFunctionCalling:
		return p.invokingOnDemand(ctx, messages)
	default:
		return &agent.Context{}, nil
	}
}

// invokingBeforeAI implements automatic search and context injection.
func (p *Provider) invokingBeforeAI(ctx context.Context, messages []agent.Message) (*agent.Context, error) {
	// Build query from memory and current messages
	query := p.extractTextFromMessages(messages)
	if query == "" {
		return &agent.Context{}, nil
	}

	// Perform search
	results, err := p.search(ctx, query)
	if err != nil {
		// Log error but don't fail the invocation
		// In production, consider using a proper logger
		return &agent.Context{}, nil
	}

	if len(results) == 0 {
		return &agent.Context{}, nil
	}

	// Limit results
	if len(results) > p.options.MaxResults {
		results = results[:p.options.MaxResults]
	}

	// Format results
	formattedResults := p.formatResults(results)
	if formattedResults == "" {
		return &agent.Context{}, nil
	}

	// Create context message with marker to prevent feedback loop
	contextMessage := chat.Message{
		Role:     chat.RoleUser,
		Contents: []chat.Content{chat.NewTextContent(formattedResults)},
		Name:     providerMarker,
	}

	return &agent.Context{
		Messages: []chat.Message{contextMessage},
	}, nil
}

// invokingOnDemand returns the search tool for on-demand invocation.
func (p *Provider) invokingOnDemand(ctx context.Context, messages []agent.Message) (*agent.Context, error) {
	return &agent.Context{
		Tools: []tool.Tool{p.searchTool},
	}, nil
}

// Invoked is called after each agent invocation.
//
// This method updates the provider's memory with the conversation
// to build better search queries for future invocations.
// Memory is only updated when RecentMessageMemoryLimit > 0.
func (p *Provider) Invoked(
	ctx context.Context,
	request []agent.Message,
	response []agent.Message,
	invokeErr error,
) error {
	// Skip memory update if memory is disabled
	if p.options.RecentMessageMemoryLimit <= 0 {
		return nil
	}

	// Skip memory update on failed invocations
	if invokeErr != nil {
		return nil
	}

	p.mu.Lock()
	defer p.mu.Unlock()

	// Collect messages that match the included roles
	var newMessages []agent.Message

	// Process request messages
	for _, msg := range request {
		if !isOurOutput(msg) && p.isRoleIncluded(msg.Role) {
			newMessages = append(newMessages, msg)
		}
	}

	// Process response messages
	for _, msg := range response {
		if p.isRoleIncluded(msg.Role) {
			newMessages = append(newMessages, msg)
		}
	}

	// Add new messages to memory
	p.memory = append(p.memory, newMessages...)

	// Trim memory to limit
	limit := p.options.RecentMessageMemoryLimit
	if len(p.memory) > limit {
		p.memory = p.memory[len(p.memory)-limit:]
	}

	return nil
}

// isRoleIncluded checks if a role is in the included roles list.
func (p *Provider) isRoleIncluded(role chat.Role) bool {
	for _, r := range p.options.RecentMessageRolesIncluded {
		if r == string(role) {
			return true
		}
	}
	return false
}

// isOurOutput checks if a message was generated by this provider.
func isOurOutput(msg agent.Message) bool {
	return msg.Name == providerMarker
}

// serializableMessage is a simplified message structure for JSON serialization.
// Using agent.SimpleMessage directly causes issues because it has different
// conversion semantics. This struct is purely for state persistence.
type serializableMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
	Name    string `json:"name,omitempty"`
}

// toSerializable converts a chat.Message to a serializable form.
func toSerializable(msg agent.Message) serializableMessage {
	return serializableMessage{
		Role:    string(msg.Role),
		Content: msg.Text(),
		Name:    msg.Name,
	}
}

// fromSerializable converts a serializable message back to a chat.Message.
func fromSerializable(sm serializableMessage) agent.Message {
	return chat.Message{
		Role:     chat.Role(sm.Role),
		Contents: []chat.Content{chat.NewTextContent(sm.Content)},
		Name:     sm.Name,
	}
}

// State represents the serializable state of the provider.
type State struct {
	Memory []serializableMessage `json:"memory"`
}

// Serialize returns the provider state as JSON.
func (p *Provider) Serialize() (json.RawMessage, error) {
	p.mu.Lock()
	defer p.mu.Unlock()

	serializable := make([]serializableMessage, len(p.memory))
	for i, msg := range p.memory {
		serializable[i] = toSerializable(msg)
	}

	state := State{
		Memory: serializable,
	}

	return json.Marshal(state)
}

// Restore restores the provider state from JSON.
func (p *Provider) Restore(data json.RawMessage) error {
	p.mu.Lock()
	defer p.mu.Unlock()

	var state State
	if err := json.Unmarshal(data, &state); err != nil {
		return err
	}

	p.memory = make([]agent.Message, len(state.Memory))
	for i, sm := range state.Memory {
		p.memory[i] = fromSerializable(sm)
	}

	return nil
}

// NewFromState creates a provider from serialized state.
func NewFromState(search SearchFunc, state json.RawMessage, opts ...Option) (*Provider, error) {
	p := New(search, opts...)
	if err := p.Restore(state); err != nil {
		return nil, err
	}
	return p, nil
}

// ClearMemory removes all messages from the provider's memory.
func (p *Provider) ClearMemory() {
	p.mu.Lock()
	defer p.mu.Unlock()
	p.memory = make([]agent.Message, 0)
}

// MemorySize returns the number of messages in the provider's memory.
func (p *Provider) MemorySize() int {
	p.mu.Lock()
	defer p.mu.Unlock()
	return len(p.memory)
}

// Compile-time interface check.
var _ agent.ContextProviderWithLifecycle = (*Provider)(nil)
